name: Example Request
description: Submit a request for an example
title: '[Example Request]: '
labels: ['Example Request']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Need an example of how to do something with tldraw?
  - type: textarea
    id: description
    attributes:
      label: What's the example?
      description: Please describe the example. What would you like to see?
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/tldraw/tldraw/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
